import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/Navbar/MainMenu"; // Import menu
import Breadcrumb from "@/components/Breadcrumb"; // Import breadcrumb
import Preloader from "@/components/Preloader"; // Import preloader

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Preloader - shows first for 2-3 seconds */}
        <Preloader />
        
        {/* Navigation Menu at the top */}
        <NavigationMenu />
        
        {/* Breadcrumb under the menu */}
        <Breadcrumb />
        
        {/* Your main content */}
        {children}
      </body>
    </html>
  );
}